In [1]:
from random import random
from functools import reduce
from collections import namedtuple
from queue import PriorityQueue, SimpleQueue, LifoQueue

import numpy as np

In [2]:
PROBLEM_SIZE = 5
NUM_SETS = 20
SETS = tuple(np.array([random() < .2 for _ in range(PROBLEM_SIZE)]) for _ in range(NUM_SETS))
State = namedtuple('State', ['taken', 'not_taken'])

In [3]:
type(SETS[0])

numpy.ndarray

In [4]:
def goal_check(state):
    return np.all(reduce(np.logical_or, [SETS[i] for i in state.taken], np.array([False for _ in range(PROBLEM_SIZE)])))

In [5]:
assert goal_check(State(set(range(NUM_SETS)), set())), "Probelm not solvable"

In [6]:
def compute_hash(tile):
    n = 0
    for i in range(PROBLEM_SIZE):
        n = 2 * n + tile[i]
    return int(n)

In [7]:
def distance(state):
    return PROBLEM_SIZE - sum(
        reduce(
            np.logical_or,
            [SETS[i] for i in state.taken],
            np.array([False for _ in range(PROBLEM_SIZE)]),
        ))

In [8]:
class MyTile:
    def __init__(self, data):
        self.data = data

    def __eq__(self, other):
        if isinstance(other, MyTile):
            return (self.data == other.data).all()
        return False
    
    def __ne__(self, other):
        if isinstance(other, MyTile):
            return (self.data != other.data).all()
        return True
    
    def __hash__(self):
        return compute_hash(self.data)

In [16]:
tiles_set = set()
tiles = list(map(lambda t : MyTile(t), SETS))

for tile in tiles:
    tiles_set.add(tile)

tiles = tuple(map(lambda t : t.data, tiles_set))
print(tiles)
print(SETS)


(array([False, False, False, False, False]), array([False, False, False, False,  True]), array([False, False, False,  True, False]), array([False, False,  True, False, False]), array([False,  True, False, False, False]), array([False,  True, False,  True, False]), array([ True, False, False, False, False]), array([ True, False, False,  True, False]))
(array([False,  True, False,  True, False]), array([ True, False, False,  True, False]), array([False, False, False,  True, False]), array([False, False, False, False, False]), array([False, False, False, False,  True]), array([False, False, False, False, False]), array([False, False, False, False, False]), array([False,  True, False, False, False]), array([False, False, False, False, False]), array([ True, False, False, False, False]), array([False, False, False, False, False]), array([False, False, False,  True, False]), array([False, False,  True, False, False]), array([False, False, False, False, False]), array([False,  True, False, Fa

In [17]:
initial_taken = set()
initial_not_taken = set(range(len(tiles_set)))

In [18]:
for i in range(PROBLEM_SIZE):
    counter =0
    pos = -1
    for j in range(NUM_SETS):
        if SETS[j][i]:
            counter+= 1
            if counter > 1:
                break
            pos = j
    if counter == 1:
        initial_taken.put(pos)
        initial_not_taken.remove(pos)

AttributeError: 'set' object has no attribute 'put'

In [227]:
initial_taken

set()

In [9]:
frontier = SimpleQueue()
frontier.put(State(set(), set(range(NUM_SETS))))
counter = 0

In [10]:
current_state = frontier.get()
while not goal_check(current_state):
    counter += 1
    for action in current_state[1]:
        new_state = State(current_state.taken ^ {action}, current_state.not_taken ^ {action})
        frontier.put(new_state)
    current_state = frontier.get()
sum_vec = []
print(f"Solved in {counter:,} steps")

Solved in 20,184 steps


In [11]:
current_state.taken

{2, 5, 7, 9}

In [12]:
SETS

(array([False, False, False, False, False]),
 array([False, False, False, False, False]),
 array([False, False, False,  True, False]),
 array([False, False, False, False, False]),
 array([False, False, False,  True, False]),
 array([False, False, False, False,  True]),
 array([False, False, False, False, False]),
 array([ True,  True, False, False, False]),
 array([False, False, False, False, False]),
 array([False, False,  True, False, False]),
 array([False, False, False, False,  True]),
 array([ True,  True, False, False, False]),
 array([False, False, False, False, False]),
 array([False, False, False,  True, False]),
 array([False, False, False, False, False]),
 array([False, False, False, False, False]),
 array([ True, False,  True, False, False]),
 array([False, False, False, False,  True]),
 array([False, False, False, False, False]),
 array([False, False, False, False, False]))

In [13]:
frontier = PriorityQueue()
frontier.put(State(set(), set(range(NUM_SETS))))
counter = 0

In [14]:
current_state2 = frontier.get()
while not goal_check(current_state2):
    counter += 1
    print("STO AGG COUNTER")
    for action in current_state2[1]:
        new_state = State(current_state2.taken ^- -à {action}, current_state2.not_taken ^ {action})
        frontier.put([len(current_state2.taken)+distance(new_state),new_state])
    current_state2 = frontier.get()[1]

print(f"Solved in {counter:,} steps {len(current_state2.taken)} solution {current_state2.taken}")

STO AGG COUNTER
STO AGG COUNTER
STO AGG COUNTER
STO AGG COUNTER
STO AGG COUNTER
STO AGG COUNTER
STO AGG COUNTER
STO AGG COUNTER
STO AGG COUNTER
STO AGG COUNTER
STO AGG COUNTER
STO AGG COUNTER
STO AGG COUNTER
STO AGG COUNTER
STO AGG COUNTER
STO AGG COUNTER
STO AGG COUNTER
STO AGG COUNTER
STO AGG COUNTER
STO AGG COUNTER
STO AGG COUNTER
STO AGG COUNTER
STO AGG COUNTER
STO AGG COUNTER
STO AGG COUNTER
STO AGG COUNTER
STO AGG COUNTER
STO AGG COUNTER
STO AGG COUNTER
STO AGG COUNTER
Solved in 30 steps 4 solution {16, 13, 11, 5}


In [233]:
print(current_state.taken)
print(current_state2.taken)

{17, 27, 15}
{17, 27, 15}


In [234]:
[print(SETS[asd]) for asd in current_state2.taken]

[False  True False False  True  True False  True  True False False  True
 False  True  True]
[False False  True  True False False False False False  True False False
  True False False]
[ True False  True False  True False  True False False False  True  True
 False False False]


[None, None, None]

In [235]:
SETS

(array([False,  True, False,  True, False,  True, False, False, False,
        False, False, False,  True, False,  True]),
 array([False, False,  True, False,  True, False, False, False, False,
        False,  True, False, False, False, False]),
 array([False, False, False, False,  True, False, False, False, False,
        False, False, False,  True,  True, False]),
 array([False, False, False,  True,  True,  True,  True, False, False,
        False,  True, False, False,  True,  True]),
 array([False,  True, False, False, False, False,  True, False, False,
         True, False, False, False, False,  True]),
 array([False, False,  True, False, False, False,  True, False, False,
        False,  True, False, False, False, False]),
 array([False, False, False,  True, False, False, False, False,  True,
        False, False,  True, False, False, False]),
 array([False, False, False, False, False, False, False,  True,  True,
         True, False, False, False, False,  True]),
 array([ True,  